// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package director

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "serviceweaver/internal/director/DirectorServerInterface",
		Iface: reflect.TypeOf((*DirectorServerInterface)(nil)).Elem(),
		Impl:  reflect.TypeOf(DirectorServerComponent{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return directorServerInterface_local_stub{impl: impl.(DirectorServerInterface), tracer: tracer, getDirectorByIdMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "serviceweaver/internal/director/DirectorServerInterface", Method: "GetDirectorById", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return directorServerInterface_client_stub{stub: stub, getDirectorByIdMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "serviceweaver/internal/director/DirectorServerInterface", Method: "GetDirectorById", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return directorServerInterface_server_stub{impl: impl.(DirectorServerInterface), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return directorServerInterface_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[DirectorServerInterface] = (*DirectorServerComponent)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*DirectorServerComponent)(nil)

// Local stub implementations.

type directorServerInterface_local_stub struct {
	impl                   DirectorServerInterface
	tracer                 trace.Tracer
	getDirectorByIdMetrics *codegen.MethodMetrics
}

// Check that directorServerInterface_local_stub implements the DirectorServerInterface interface.
var _ DirectorServerInterface = (*directorServerInterface_local_stub)(nil)

func (s directorServerInterface_local_stub) GetDirectorById(ctx context.Context, a0 *GetDirectorByIdRequest) (r0 *GetDirectorResponse, err error) {
	// Update metrics.
	begin := s.getDirectorByIdMetrics.Begin()
	defer func() { s.getDirectorByIdMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "director.DirectorServerInterface.GetDirectorById", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetDirectorById(ctx, a0)
}

// Client stub implementations.

type directorServerInterface_client_stub struct {
	stub                   codegen.Stub
	getDirectorByIdMetrics *codegen.MethodMetrics
}

// Check that directorServerInterface_client_stub implements the DirectorServerInterface interface.
var _ DirectorServerInterface = (*directorServerInterface_client_stub)(nil)

func (s directorServerInterface_client_stub) GetDirectorById(ctx context.Context, a0 *GetDirectorByIdRequest) (r0 *GetDirectorResponse, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getDirectorByIdMetrics.Begin()
	defer func() { s.getDirectorByIdMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "director.DirectorServerInterface.GetDirectorById", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetDirectorByIdRequest_e6d178b1(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetDirectorResponse_4be0fb6c(dec)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.22.0 (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type directorServerInterface_server_stub struct {
	impl    DirectorServerInterface
	addLoad func(key uint64, load float64)
}

// Check that directorServerInterface_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*directorServerInterface_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s directorServerInterface_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "GetDirectorById":
		return s.getDirectorById
	default:
		return nil
	}
}

func (s directorServerInterface_server_stub) getDirectorById(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *GetDirectorByIdRequest
	a0 = serviceweaver_dec_ptr_GetDirectorByIdRequest_e6d178b1(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetDirectorById(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetDirectorResponse_4be0fb6c(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type directorServerInterface_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that directorServerInterface_reflect_stub implements the DirectorServerInterface interface.
var _ DirectorServerInterface = (*directorServerInterface_reflect_stub)(nil)

func (s directorServerInterface_reflect_stub) GetDirectorById(ctx context.Context, a0 *GetDirectorByIdRequest) (r0 *GetDirectorResponse, err error) {
	err = s.caller("GetDirectorById", ctx, []any{a0}, []any{&r0})
	return
}

// Encoding/decoding implementations.

func serviceweaver_enc_ptr_GetDirectorByIdRequest_e6d178b1(enc *codegen.Encoder, arg *GetDirectorByIdRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetDirectorByIdRequest_e6d178b1(dec *codegen.Decoder) *GetDirectorByIdRequest {
	if !dec.Bool() {
		return nil
	}
	var res GetDirectorByIdRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetDirectorResponse_4be0fb6c(enc *codegen.Encoder, arg *GetDirectorResponse) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetDirectorResponse_4be0fb6c(dec *codegen.Decoder) *GetDirectorResponse {
	if !dec.Bool() {
		return nil
	}
	var res GetDirectorResponse
	dec.DecodeProto(&res)
	return &res
}
