// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package movie

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "serviceweaver/internal/movie/MovieServerInterface",
		Iface: reflect.TypeOf((*MovieServerInterface)(nil)).Elem(),
		Impl:  reflect.TypeOf(MovieServerComponent{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return movieServerInterface_local_stub{impl: impl.(MovieServerInterface), tracer: tracer, getMovieByDirectorMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "serviceweaver/internal/movie/MovieServerInterface", Method: "GetMovieByDirector", Remote: false}), getMovieByIdMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "serviceweaver/internal/movie/MovieServerInterface", Method: "GetMovieById", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return movieServerInterface_client_stub{stub: stub, getMovieByDirectorMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "serviceweaver/internal/movie/MovieServerInterface", Method: "GetMovieByDirector", Remote: true}), getMovieByIdMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "serviceweaver/internal/movie/MovieServerInterface", Method: "GetMovieById", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return movieServerInterface_server_stub{impl: impl.(MovieServerInterface), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return movieServerInterface_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[MovieServerInterface] = (*MovieServerComponent)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*MovieServerComponent)(nil)

// Local stub implementations.

type movieServerInterface_local_stub struct {
	impl                      MovieServerInterface
	tracer                    trace.Tracer
	getMovieByDirectorMetrics *codegen.MethodMetrics
	getMovieByIdMetrics       *codegen.MethodMetrics
}

// Check that movieServerInterface_local_stub implements the MovieServerInterface interface.
var _ MovieServerInterface = (*movieServerInterface_local_stub)(nil)

func (s movieServerInterface_local_stub) GetMovieByDirector(ctx context.Context, a0 *GetMovieByDirectorRequest) (r0 *GetMovieResponse, err error) {
	// Update metrics.
	begin := s.getMovieByDirectorMetrics.Begin()
	defer func() { s.getMovieByDirectorMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "movie.MovieServerInterface.GetMovieByDirector", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetMovieByDirector(ctx, a0)
}

func (s movieServerInterface_local_stub) GetMovieById(ctx context.Context, a0 *GetMovieByIdRequest) (r0 *GetMovieResponse, err error) {
	// Update metrics.
	begin := s.getMovieByIdMetrics.Begin()
	defer func() { s.getMovieByIdMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "movie.MovieServerInterface.GetMovieById", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetMovieById(ctx, a0)
}

// Client stub implementations.

type movieServerInterface_client_stub struct {
	stub                      codegen.Stub
	getMovieByDirectorMetrics *codegen.MethodMetrics
	getMovieByIdMetrics       *codegen.MethodMetrics
}

// Check that movieServerInterface_client_stub implements the MovieServerInterface interface.
var _ MovieServerInterface = (*movieServerInterface_client_stub)(nil)

func (s movieServerInterface_client_stub) GetMovieByDirector(ctx context.Context, a0 *GetMovieByDirectorRequest) (r0 *GetMovieResponse, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMovieByDirectorMetrics.Begin()
	defer func() { s.getMovieByDirectorMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "movie.MovieServerInterface.GetMovieByDirector", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetMovieByDirectorRequest_72d179f2(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetMovieResponse_9f0c9523(dec)
	err = dec.Error()
	return
}

func (s movieServerInterface_client_stub) GetMovieById(ctx context.Context, a0 *GetMovieByIdRequest) (r0 *GetMovieResponse, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getMovieByIdMetrics.Begin()
	defer func() { s.getMovieByIdMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "movie.MovieServerInterface.GetMovieById", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetMovieByIdRequest_07781373(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_GetMovieResponse_9f0c9523(dec)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.22.0 (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type movieServerInterface_server_stub struct {
	impl    MovieServerInterface
	addLoad func(key uint64, load float64)
}

// Check that movieServerInterface_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*movieServerInterface_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s movieServerInterface_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "GetMovieByDirector":
		return s.getMovieByDirector
	case "GetMovieById":
		return s.getMovieById
	default:
		return nil
	}
}

func (s movieServerInterface_server_stub) getMovieByDirector(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *GetMovieByDirectorRequest
	a0 = serviceweaver_dec_ptr_GetMovieByDirectorRequest_72d179f2(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetMovieByDirector(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetMovieResponse_9f0c9523(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s movieServerInterface_server_stub) getMovieById(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 *GetMovieByIdRequest
	a0 = serviceweaver_dec_ptr_GetMovieByIdRequest_07781373(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetMovieById(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_GetMovieResponse_9f0c9523(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type movieServerInterface_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that movieServerInterface_reflect_stub implements the MovieServerInterface interface.
var _ MovieServerInterface = (*movieServerInterface_reflect_stub)(nil)

func (s movieServerInterface_reflect_stub) GetMovieByDirector(ctx context.Context, a0 *GetMovieByDirectorRequest) (r0 *GetMovieResponse, err error) {
	err = s.caller("GetMovieByDirector", ctx, []any{a0}, []any{&r0})
	return
}

func (s movieServerInterface_reflect_stub) GetMovieById(ctx context.Context, a0 *GetMovieByIdRequest) (r0 *GetMovieResponse, err error) {
	err = s.caller("GetMovieById", ctx, []any{a0}, []any{&r0})
	return
}

// Encoding/decoding implementations.

func serviceweaver_enc_ptr_GetMovieByDirectorRequest_72d179f2(enc *codegen.Encoder, arg *GetMovieByDirectorRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetMovieByDirectorRequest_72d179f2(dec *codegen.Decoder) *GetMovieByDirectorRequest {
	if !dec.Bool() {
		return nil
	}
	var res GetMovieByDirectorRequest
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetMovieResponse_9f0c9523(enc *codegen.Encoder, arg *GetMovieResponse) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetMovieResponse_9f0c9523(dec *codegen.Decoder) *GetMovieResponse {
	if !dec.Bool() {
		return nil
	}
	var res GetMovieResponse
	dec.DecodeProto(&res)
	return &res
}

func serviceweaver_enc_ptr_GetMovieByIdRequest_07781373(enc *codegen.Encoder, arg *GetMovieByIdRequest) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		enc.EncodeProto(arg)
	}
}

func serviceweaver_dec_ptr_GetMovieByIdRequest_07781373(dec *codegen.Decoder) *GetMovieByIdRequest {
	if !dec.Bool() {
		return nil
	}
	var res GetMovieByIdRequest
	dec.DecodeProto(&res)
	return &res
}
